### ISSUE TITLE
As a dev, I need an environment

### ISSUE THREAD

**Issue by labofoz** [labofoz/labofoz.com#1]
## Scope
- [ ] I can run `npm start` to code locally
- [ ] I can run `npm run build` to build the project
- [ ] I can run `npm run deploy` to deploy to Firebase

## Tasks
- [ ] Create the package.json
- [x] Create README
- [ ] Add `/src/index.pug`
- [ ] Add a simple stylus sheet
- [ ] Add and setup vue
