### ISSUE TITLE
As a dev, I need an environment

### ISSUE THREAD

**Issue by labofoz** [labofoz/labofoz.com#1]
## Scope
- [x] I can start a development server with `npm start`
- [x] I can code with Stylus and Pug
- [x] There's a readme to remind me how to set all this up

## Tasks
- [x] Setup nuxt
- [x] Setup stylus and pug
- [x] Replace all HTML/Stylus

**Comment by labofoz** [comment]
Here's roughly where we're at!

![image](https://user-images.githubusercontent.com/52610021/60762218-abdf4300-a00f-11e9-9529-4622401cc27a.png)
