### ISSUE TITLE
As a visitor, I need content

### ISSUE THREAD

**Issue by labofoz** [labofoz/labofoz.com#2]
I want to be a bit more spontaneous with this story, so scopes are intentionally left very broad:

## Scope
- [x] There's a site on labofoz.com
- [x] I know how to contact the lab
- [x] The site works responsively
- ~ I know what the site is about~ Going to build into WordPress instead
- ~I can sign up to a newsletter~ Going to use WordPress instead

## Tasks
- [x] Add tilt.js and make the logo follow the cursor as the user scrolls
- [x] Separate out the logo as an SVG
- [x] Animate the logo
- [x] Link to external sites for now
- [x] Upload to Firebase
- [x] Redirect domains
- [x] Display tweets
- [x] Use a masonry layout
- [x] Show relevant tweets when clicked
- [x] When scrolling below the hero show main nav bar
- [x] Add Google Analytics

**Comment by labofoz** [comment]
Here's where I ended up, I'm going to start a WordPress theme instead. I really feel strongly about WordPress and machine learning:

![ezgif-4-7157ce66f7e6](https://user-images.githubusercontent.com/52610021/60843627-12896b80-a18c-11e9-889e-f02cfdc818b9.gif)
